Added env in deploy to server workflow

diff --git a/.github/workflows/deploy-to-server.yml b/.github/workflows/deploy-to-server.yml
--- a/.github/workflows/deploy-to-server.yml
+++ b/.github/workflows/deploy-to-server.yml
@@ -6,6 +6,9 @@ on:
 jobs:
     deploy:
         runs-on: ubuntu-latest
+        env:
+            DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
+            DOCKER_TAG: ${{ github.sha }}
         steps:
             - name: Checkout Code
               uses: actions/checkout@v4
@@ -20,9 +23,15 @@ jobs:
                       echo "Starting Deployment"
                       mkdir -p devops
                       sudo apt-get update
-                      sudo apt-get install docker.io docker-compose-v2 -y
-                      sudo usermod -aG docker $USER && newgrp docker
-                      echo ${USER}
+                      if ! command -v docker &> /dev/null; then
+                        echo "Docker not found. Installing..."
+                        sudo apt install -y docker.io
+                        sudo systemctl enable docker
+                        sudo systemctl start docker
+                        sudo usermod -aG docker $USER
+                      else
+                        echo "Docker already installed. Skipping..."
+                      fi
 
             - name: Copy docker-compose.yml to remote server
               uses: appleboy/scp-action@v0.1.3
@@ -41,8 +50,5 @@ jobs:
                   key: ${{ secrets.EC2_SSH_KEY }}
                   script: |
                       echo "Running App"
-                      echo ${USER}
-                      export DOCKERHUB_USER=${{ vars.DOCKERHUB_USER }}
-                      export DOCKER_TAG=${{ github.sha }}
                       echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ vars.DOCKERHUB_USER }} --password-stdin
                       cd ~/devops && docker compose down && docker compose up -d --build --force-recreate
